---

name: Quality Assurance

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  xmlllint:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libxml2-utils
      - uses: actions/checkout@v5
      - run: find files -type f -name '*.xml' -exec xmllint --noout --pedantic {} \;

...
